import type { Metadata } from 'next'
import { Nunito, Rowdies } from 'next/font/google'
import './globals.scss'
import ThemeProvider from './_providers/ThemeProvider'

const nunito = Nunito({
	variable: '--font-nunito',
	subsets: ['latin'],
})

const rowdies = Rowdies({
	variable: '--font-rowdies',
	weight: ['300', '400', '700'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${nunito.variable} ${rowdies.variable}`}>
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	)
}
